//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greennit.Models
{
    using Foolproof;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Comments = new HashSet<Comment>();
            UpVotes = 0;
            DownVotes = 0;
            Author = "Anonymous";
        }

        public int ID { get; set; }

        [Display(Name = "Content Type")]
        [Required]
        //[StringLength(50, MinimumLength = 2)]
        public int ContentTypeID { get; set; }

        [Display(Name = "Title")]
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string Title { get; set; }

        [Display(Name = "Description")]
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string Description { get; set; }

        [Display(Name = "Post By")]
        [StringLength(50, MinimumLength = 2)]
        [DisplayFormat(NullDisplayText = "Anonymous")]
        public string Author { get; set; }

        [Display(Name = "Image URL")]
        [DataType(DataType.ImageUrl)]
        [DisplayFormat(NullDisplayText = "N/A")]
        [RequiredIf("ContentTypeID", 3, ErrorMessage = "Please add an image URL")]
        public string Image { get; set; }

        [Display(Name = "Website URL")]
        [StringLength(500, MinimumLength = 2)]
        [DisplayFormat(NullDisplayText = "N/A")]
        [Url]
        [RequiredIf("ContentTypeID", 2, ErrorMessage = "Please add a webpage")]
        public string Website { get; set; }

        [Display(Name = "Youtube Video ID")]
        [DisplayFormat(NullDisplayText = "N/A")]
        [RegularExpression("([a-zA-Z0-9_-]{11})", ErrorMessage = "This is not a valid 11 character YouTube ID.")]
        [RequiredIf("ContentTypeID", 1, ErrorMessage = "Please add a YouTube ID")]
        public string Video { get; set; }

        [Display(Name = "Article")]
        [DisplayFormat(NullDisplayText = "N/A")]
        [DataType(DataType.MultilineText)]
        [RequiredIf("ContentTypeID", 4, ErrorMessage = "Please add some text to your article!")]
        public string Text { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }

        [Display(Name = "Post Type")]
        public virtual ContentType ContentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
